Repository advanced-cms/advanced-reviews, pull requests merged in 2021-06, with the labels that each got.

#194 boyscout: Refactor custom loading of content
  src/external-reviews/CustomContentLoaderInitialization.cs
  src/external-reviews/DraftContentAreaPreview/PublishedStateAssessorDecorator.cs
  src/external-reviews/ExternalReview.cs
Labels: refactoring

#195 Proxy images through custom image handler
  src/alloy/Views/TestContentPage/Index.cshtml
  src/external-reviews/ImageProxy/GlobalRouteInitialization.cs
  src/external-reviews/ImageProxy/ImageProxyExtensions.cs
  src/external-reviews/ImageProxy/ImageProxyHandler.cs
  src/external-reviews/ImageProxy/ImageProxyRouteHandler.cs
  src/external-reviews/PreviewUrlResolver.cs
Labels: bug

#193 Make sure ContentLoading event swap the `content`
  src/external-reviews/CustomContentLoaderInitialization.cs
  src/external-reviews/DraftContentAreaPreview/PublishedStateAssessorDecorator.cs
  src/external-reviews/ExternalReview.cs
Labels: bug

#197 Allow to configure prolong value
  README.md
  src/alloy/Business/AlloyReviews/ExternalReviewOptionsInitialization.cs
  src/external-reviews/EmbededLanguages/advancedexternalreviews_EN.xml
  src/external-reviews/EmbededLanguages/advancedexternalreviews_SV.xml
  src/external-reviews/ExternalReviewOptions.cs
  src/external-reviews/ManageLinks/ExternalReviewLinksManageComponent.cs
  src/ui/.storybook/externalResources.json
  src/ui/externalResources.d.ts
  src/ui/src/external-reviews-manage-links/external-review-manage-links-edit.tsx
  src/ui/src/external-reviews-manage-links/external-review-manage-links-widget.tsx
  src/ui/src/external-reviews-manage-links/external-review-manage-links.stories.tsx
  src/ui/src/external-reviews-manage-links/external-review-manage-links.tsx
Labels: enhancement
